[archive] 
status=restored 
mode=historical 

[research] 
operator=turing 
project=ultra 

[human] 
reference=mitnick 

[crypto] 
reference=schneier 
algorithm=blowfish 

[notes] 
facility_identifier=missing